// <auto-generated />
using System;
using DictionaryService.Infrastructure.Persistence.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DictionaryService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    partial class DictionaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Dictionary")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_definition");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_dictionary_definition_dictionary_entry_id");

                    b.ToTable("DictionaryDefinition", "Dictionary");
                });

            modelBuilder.Entity("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Headword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("headword");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pronunciation");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_entry");

                    b.HasIndex("Headword", "PartOfSpeech")
                        .IsUnique()
                        .HasDatabaseName("ix_dictionary_entry_headword_part_of_speech");

                    b.ToTable("DictionaryEntry", "Dictionary");
                });

            modelBuilder.Entity("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DictionaryDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_definition_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_example");

                    b.HasIndex("DictionaryDefinitionId")
                        .HasDatabaseName("ix_dictionary_example_dictionary_definition_id");

                    b.ToTable("DictionaryExample", "Dictionary");
                });

            modelBuilder.Entity("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryDefinition", b =>
                {
                    b.HasOne("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryEntry", null)
                        .WithMany("Definitions")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dictionary_definition_dictionary_entries_dictionary_entry_id");
                });

            modelBuilder.Entity("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryExample", b =>
                {
                    b.HasOne("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryDefinition", null)
                        .WithMany("Examples")
                        .HasForeignKey("DictionaryDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dictionary_example_dictionary_definition_dictionary_definitio");
                });

            modelBuilder.Entity("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryDefinition", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("DictionaryService.Domain.Aggregates.DictionaryEntries.Models.DictionaryEntry", b =>
                {
                    b.Navigation("Definitions");
                });
#pragma warning restore 612, 618
        }
    }
}
