<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Infrastructure\**" />
    <EmbeddedResource Remove="Infrastructure\**" />
    <None Remove="Infrastructure\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VocabularyService.Application\VocabularyService.Application.csproj" />
    <ProjectReference Include="..\VocabularyService.Infrastructure\VocabularyService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
