// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VocabularyService.Infrastructure.Persistence.DataContext;

#nullable disable

namespace VocabularyService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VocabularyContext))]
    partial class VocabularyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Vocabulary")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VocabularyService.Domain.Aggregates.Vocabulary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cloze")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cloze");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("definition");

                    b.Property<string>("Headword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("headword");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pronunciation");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("translation");

                    b.HasKey("Id")
                        .HasName("pk_vocabulary");

                    b.ToTable("Vocabulary", "Vocabulary");
                });

            modelBuilder.Entity("VocabularyService.Domain.Aggregates.VocabularyExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<Guid?>("VocabularyId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id")
                        .HasName("pk_vocabulary_example");

                    b.HasIndex("VocabularyId")
                        .HasDatabaseName("ix_vocabulary_example_vocabulary_id");

                    b.ToTable("VocabularyExample", "Vocabulary");
                });

            modelBuilder.Entity("VocabularyService.Domain.Aggregates.Vocabulary", b =>
                {
                    b.OwnsOne("BuildingBlocks.Domain.ValueObjects.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("VocabularyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_created_at");

                            b1.Property<Guid?>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("audit_created_by");

                            b1.Property<DateTimeOffset?>("LastModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_last_modified_at");

                            b1.Property<Guid?>("LastModifiedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("audit_last_modified_by");

                            b1.HasKey("VocabularyId");

                            b1.ToTable("Vocabulary", "Vocabulary");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyId")
                                .HasConstraintName("fk_vocabulary_vocabulary_id");
                        });

                    b.OwnsOne("BuildingBlocks.Domain.ValueObjects.SoftDeleteInfo", "SoftDelete", b1 =>
                        {
                            b1.Property<Guid>("VocabularyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("soft_delete_deleted_at");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("soft_delete_deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("soft_delete_is_deleted");

                            b1.HasKey("VocabularyId");

                            b1.ToTable("Vocabulary", "Vocabulary");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyId")
                                .HasConstraintName("fk_vocabulary_vocabulary_id");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("SoftDelete")
                        .IsRequired();
                });

            modelBuilder.Entity("VocabularyService.Domain.Aggregates.VocabularyExample", b =>
                {
                    b.HasOne("VocabularyService.Domain.Aggregates.Vocabulary", null)
                        .WithMany("Examples")
                        .HasForeignKey("VocabularyId")
                        .HasConstraintName("fk_vocabulary_example_vocabulary_vocabulary_id");

                    b.OwnsOne("BuildingBlocks.Domain.ValueObjects.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("VocabularyExampleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_created_at");

                            b1.Property<Guid?>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("audit_created_by");

                            b1.Property<DateTimeOffset?>("LastModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_last_modified_at");

                            b1.Property<Guid?>("LastModifiedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("audit_last_modified_by");

                            b1.HasKey("VocabularyExampleId");

                            b1.ToTable("VocabularyExample", "Vocabulary");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyExampleId")
                                .HasConstraintName("fk_vocabulary_example_vocabulary_example_id");
                        });

                    b.OwnsOne("BuildingBlocks.Domain.ValueObjects.SoftDeleteInfo", "SoftDelete", b1 =>
                        {
                            b1.Property<Guid>("VocabularyExampleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("soft_delete_deleted_at");

                            b1.Property<Guid?>("DeletedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("soft_delete_deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("soft_delete_is_deleted");

                            b1.HasKey("VocabularyExampleId");

                            b1.ToTable("VocabularyExample", "Vocabulary");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyExampleId")
                                .HasConstraintName("fk_vocabulary_example_vocabulary_example_id");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("SoftDelete")
                        .IsRequired();
                });

            modelBuilder.Entity("VocabularyService.Domain.Aggregates.Vocabulary", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
